# This file is part of the Dive framework.
#
# Dive is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Additional permission under section 7 of the GNU General Public
# License, version 3 ("GPLv3"):
#
# If you convey this file as part of a work that contains a
# configuration script generated by Autoconf, you may do so under
# terms of your choice.
#
# Dive is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Dive.  If not, see <http://www.gnu.org/licenses/>.


# -------#
# README #
# -------#

# This file allow Autoconf to compile ``.ice'' files.
# It requires:
# - that you include *before* this file init.mk or make sure that
#   any global variable can be used with the += syntax.
# - that you called ICE_CXX in the configure to initialize
#   Ice specific variables. See auto-ice.m4 for more information.
#
# Do not include this file in a Makefile.am which is building
# software that should be built if Ice is disabled.
# I.e: do not mix software that requires Ice and software that
# does not need it.

# -----#
# TODO #
# -----#

# - Support all Ice compatible languages (only C++ is supported for now).



# Add ``.ice'' to the list of known suffixes.
SUFFIXES += .ice

# Force the compiled to search for headers in the current
# build directory. Required to find the generated headers.
AM_CPPFLAGS += 	-I$(builddir)

# Generate header/source file from the ``.ice'' file.
.ice.hh:
.ice.cc:
	$(SLICE2CPP) $(SLICE2CPPFLAGS) \
		--source-ext cc $<


# Override all in order to prevent the Ice modules to be built
# if Ice is not available.
if !ICE
all:
	@echo -n "Ice not supported. " && \
	echo "Please re-run configure with --with-ice=yes flag."
endif
